name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Merkle Proof on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p data
        echo '{"data":["data1","data2","data3"]}' > data/merkleInput.json
        npm run start-linux

    - name: Run Merkle Proof on Windows
      if: matrix.os == 'windows-latest'
      run: |
        mkdir data
        echo {"data":["data1","data2","data3"]} > data/merkleInput.json
        npm run start-windows
